// Generate source-owned structural identities without reading tenant records.
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PGlite } from '@electric-sql/pglite';
import { demoStructuralHash, demoStructuralCategoryEvidence, readDemoStructuralContract } from '../src/demo/schemaLineage';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const journal=JSON.parse(readFileSync(path.join(root,'drizzle/meta/_journal.json'),'utf8')) as { entries: { idx: number; tag: string }[] };
const identities: { version: number; tag: string; sqlHash: string; structuralHash: string; categories: Awaited<ReturnType<typeof demoStructuralCategoryEvidence>> }[]=[];
let hrIndexes: {name:string;table:string;definition:string}[]=[];
let legacyRoleIndex: {table:string;name:string;definition:string;valid:boolean;ready:boolean;immediate:boolean}|undefined;
const client=new PGlite();
let ownedTables: string[]=[];
let ownedFunctions: string[]=[];
try {
  for(const entry of journal.entries){
    const sql=readFileSync(path.join(root,'drizzle',entry.tag+'.sql'),'utf8').trim();
    await client.exec(sql);
    const contract=await readDemoStructuralContract(client);
    identities.push({version:entry.idx,tag:entry.tag,sqlHash:createHash('sha256').update(sql).digest('hex'),structuralHash:await demoStructuralHash(contract),categories:await demoStructuralCategoryEvidence(contract)});
    ownedTables=contract.tables;
    ownedFunctions=contract.functions.map(row=>row.signature);
    if(entry.idx===72)legacyRoleIndex=contract.indexes.find(index=>index.name==='uq_role_master_name');
    if(entry.idx===118){
      hrIndexes=(await client.query<{name:string;table:string;definition:string}>("select indexname as name,tablename as \"table\",indexdef as definition from pg_indexes where schemaname='public' and indexname in ('uq_hr_business_unit_code','uq_hr_business_unit_tenant_id','uq_hr_position_code','uq_hr_position_tenant_id') order by indexname")).rows;
    }
  }
} finally { await client.close(); }
const hr=identities.find(entry=>entry.version===118&&entry.tag==='0118_classy_ronan');
const prior=identities.find(entry=>entry.version===117);
if(!hr||!prior||hrIndexes.length!==4||!legacyRoleIndex||legacyRoleIndex.table!=='role') throw new Error('The bounded compatibility lineage is absent. Review the identity policy before regenerating.');
const bundle=readFileSync(path.join(root,'web/public/db/erp-system-migrations.sql'),'utf8');
const start=bundle.indexOf('-- 0118_classy_ronan\n');
if(start<0)throw new Error('Generated HR compatibility SQL is absent. Run generate:demo-schema first.');
const next=bundle.slice(start+1).search(/^-- \d{4}_/m);
const repairSql=next<0?bundle.slice(start).trim():bundle.slice(start,start+1+next).trim();
const target=path.join(root,'src/demo/schemaLineage.generated.ts');
const content='// GENERATED by scripts/generate-demo-schema-lineage.ts. Do not edit.\n'+
  'export const DEMO_SCHEMA_LINEAGE = '+JSON.stringify({identities,ownedTables,ownedFunctions,assetHashes:{'erp-system-schema.sql':createHash('sha256').update(readFileSync(path.join(root,'web/public/db/erp-system-schema.sql'),'utf8')).digest('hex'),'erp-system-migrations.sql':createHash('sha256').update(bundle).digest('hex')},legacyRoleRepair:{absentSinceVersion:73,index:legacyRoleIndex},hrRepair:{fromVersion:117,toVersion:118,tag:hr.tag,sqlHash:hr.sqlHash,sql:repairSql,indexes:hrIndexes}},null,2)+' as const;\n';
if(process.argv.includes('--check')){
  if(readFileSync(target,'utf8')!==content)throw new Error('Generated Demo schema lineage is stale. Run generate:demo-lineage.');
  console.log('Demo structural identities match '+identities.length+' canonical migration prefixes.');
}else{
  writeFileSync(target,content);
  console.log('Generated '+identities.length+' Demo structural identities and bounded HR compatibility SQL.');
}
